version: 0.1
log:
  fields:
    service: registry
storage:
    cache:
        blobdescriptor: inmemory
    filesystem:
        rootdirectory: /var/lib/registry
http:
    addr: :6000
    secret: asecretforproduction
    headers:
        X-Content-Type-Options: [nosniff]
compatibility:
  schema1:
    enabled: true
proxy:
    remoteurl: {remoteurl}
