apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: registry-perftest-mongo
  labels:
    k8s-app: perftest
spec:
  selector:
    matchLabels:
      name: perftest
  template:
    metadata:
      labels:
        name: perftest
    spec:
      containers:
      - name: registry-perftest-mongo
        image: dockerhub.akscn.io/library/mongo
        imagePullPolicy: Always
