apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: registry-perftest-httpd
  labels:
    k8s-app: perftest
spec:
  selector:
    matchLabels:
      name: perftest
  template:
    metadata:
      labels:
        name: perftest
    spec:
      containers:
      - name: registry-perftest-httpd
        image: dockerhub.akscn.io/library/httpd
        imagePullPolicy: Always
